"姓名": "张三"
"学号": "114514"
"QQ号": "114514"
"手机号码or电话号码or联系方式": "114514"
"专业": "职业法师"
"班级": "2506"
"年级": "2025级"
"特长": "腿特长"
"爱好": "乒乓球、旅游"
"学院": "教育科学学院"
"学校or院校": "南京师范大学"
"校区": "随园校区"
"邮箱": "114514@qq.com"
"身份证号": "114514"
